Repository kw-chi-community/CHIC-25-CLASSROOM-STUDENT, pull requests merged in 2025-04, with the labels that each got.

#39 ♻️ Refactor/#32 회원가입시 전화번호 추가로 입력받기
  back/db/student.js
  back/routes/studentIdRouter.js
  front/src/api/signup/checkIdAvailability.ts
  front/src/api/signup/dto/signupDto.ts
  front/src/api/signup/signup.ts
  front/src/components/PageWrapper/CenteredPageWrapper.tsx
  front/src/pages/Login/Login.tsx
  front/src/pages/SignUp/SignUp.tsx
  front/src/pages/SignUp/components/EmailVerification.tsx
Labels: ♻️ Refactor, ✨ Feature

#42 ♻️ check-time api 수정, 건물 호수 매칭 완료
  back/db/classroomInfo.js
  back/routes/classroomInfo.js
  back/routes/reservation.js
  back/routes/reserveRoom.js
  back/server.js
Labels: ♻️ Refactor

#48 ✨ Feat/#36 예약 상세 팝업 만들기
  front/src/api/login/login.ts
  front/src/api/mypage/dto/fetchProfileDataDto.ts
  front/src/api/mypage/dto/fetchReservationDetailDto.ts
  front/src/api/mypage/fetchProfileData.ts
  front/src/api/mypage/fetchReservationDetail.ts
  front/src/components/Header/BackHeader.tsx
  front/src/components/Header/MainHeader.tsx
  front/src/components/Popup/ReservationDetailPopup.tsx
  front/src/pages/Login/Login.tsx
  front/src/pages/MakeReservation/MakeReservation.tsx
  front/src/pages/MyPage/MyPage.tsx
  front/src/pages/ReservationStatus/AllScheduleDTO.ts
  front/src/pages/ReservationStatus/_components/RoomTab.tsx
  front/src/pages/ReservationStatus/_components/WeeklyTimeTable.tsx
  front/src/pages/ReservationStatus/api/fetchAllScheduleData.ts
Labels: ✨ Feature

#49 ✨ Feat/#35 AlertModal 컴포넌트 만들기
  front/src/components/Popup/AlertPopup.tsx
  front/src/pages/MakeReservation/MakeReservation.tsx
Labels: ✨ Feature

#50 강의 예약/현황/디테일 api 생성
  back/db/reservation.js
  back/routes/makereserve.js
  back/routes/reservation.js
  back/routes/reservationDetail.js
  back/routes/reservationList.js
  back/server.js
Labels: ♻️ Refactor, ✨ Feature

#51 ✨ Feat/#37 예약 목록 불러오기 + 예약 상세 팝업 띄우기
  back/routes/reservationDetail.js
  back/routes/reservationList.js
  front/src/api/mypage/dto/fetchReservationDetailDto.ts
  front/src/api/mypage/dto/fetchReservationListDto.ts
  front/src/api/mypage/fetchReservationList.ts
  front/src/components/Popup/ReservationDetailPopup.tsx
  front/src/pages/Home/components/UpcomingReservations.tsx
  front/src/pages/MakeReservation/MakeReservation.tsx
  front/src/pages/MyPage/MyPage.tsx
  front/src/pages/MyPage/components/ProfileCard.tsx
  front/src/pages/MyPage/components/ReservationList.tsx
Labels: ✨ Feature

#53 ✨ Feat/#52 마이페이지 프로필 수정 및 탈퇴하기
  front/src/App.tsx
  front/src/api/mypage/dto/fetchProfileDataDto.ts
  front/src/api/mypage/fetchProfileData.ts
  front/src/api/profile-detail/changeUserPassword.ts
  front/src/api/profile-detail/deleteUserAccount.ts
  front/src/api/profile-detail/dto/changeUserPasswordDto.ts
  front/src/api/profile-detail/dto/updateUserInformationDto.ts
  front/src/api/profile-detail/updateUserInformation.ts
  front/src/components/Input.tsx
  front/src/constants/routes.ts
  front/src/pages/MyPage/components/ProfileCard.tsx
  front/src/pages/ProfileDetail/ProfileDetail.tsx
  front/src/pages/ProfileDetail/components/ProfileActions.tsx
  front/src/pages/ProfileDetail/components/ProfileForm.tsx
Labels: ✨ Feature

#63 ✨ Feat/#61 강의실 사용 현황 페이지 api 연동 함수 및 마크업개발
  front/src/api/room-schedule/dto/fetchReservationSchedulesDto.ts
  front/src/api/room-schedule/fetchReservationSchedules.ts
  front/src/components/Input.tsx
  front/src/constants/routes.ts
  front/src/pages/Home/components/NavigationButtons.tsx
  front/src/pages/ReservationStatus/ReservationStatus.tsx
Labels: ✨ Feature

#64 🔧 Feat/#54 API 경로 수정: 예약 조회 API의 경로를 변경하여 일관성 유지
  front/src/api/make-reservation/getReservation.ts
Labels: ♻️ Refactor
