Repository kw-chi-community/CHIC-25-CLASSROOM-STUDENT, pull requests merged in 2025-03, with the labels that each got.

#11 Feat/#7
  front/src/components/Button.tsx
  front/src/components/Input.tsx
  front/src/pages/SignUp/SignUp.tsx
  front/src/pages/SignUp/api/checkIdAvailability.ts
  front/src/pages/SignUp/components/EmailVerification.tsx
Labels: ✨ Feature

#12 ♻️ Refactor/#8 비밀번호 입력 필드 추가 및 회원가입 링크 생성
  front/src/pages/Login/Login.tsx
  front/tailwind.config.js
Labels: ♻️ Refactor, ✨ Feature

#13 💄 Feat/#7 Signup 페이지 css 수정
  front/src/components/Input.tsx
  front/src/pages/SignUp/components/EmailVerification.tsx
Labels: 💄 Styles

#14 ♻️ Refactor/#8 학번 10자리 검증 로직 수정 및 광운대학교로 타이틀 변경
  front/src/pages/Login/Login.tsx
Labels: ♻️ Refactor

#16 ♻️ Refactor/#9 강의실 예약시, 건물 정보도 같이 보내기
  front/src/pages/MakeReservation/MakeReservation.tsx
Labels: ♻️ Refactor

#18 🐛 Fix/#17 api 호출시 URL 변경
  front/src/pages/SignUp/components/EmailVerification.tsx
Labels: 🐛 Fix

#20 🔨 (#19) 홈 UI 리셋
  front/src/pages/Home/Home.tsx
  front/src/pages/Home/TodayScheduleDTO.ts
  front/src/pages/Home/api/fetchTodayScheduleData.ts
Labels: ♻️ Refactor

#25 🔨 Refactor/#23 메일 내용 수정
  back/handlers/sendEmail.js
Labels: ♻️ Refactor
